before_script:
  - dnf -y --best install rust cargo

pages:
  image: asciidoctor/docker-asciidoctor
  script:
    - make html
    - mv built public
  artifacts:
    paths:
      - public
  only:
    - master
